function plotAircraft(obj)
offsets = obj.Fuselage.AeroLocations;
figure; hold on;
obj.plotWing3d('Wing',...
    'Xoffset',0,...
    'Yoffset',0,...
    'Zoffset',0);
obj.plotWing3d('HorizontalTail',...
    'Xoffset',offsets('xHT'),...
    'Yoffset',offsets('yHT'),...
    'Zoffset',offsets('zHT'));
if obj.VerticalTailGeometry.PanelCount > 0
    obj.plotWing3d('VerticalTail',...
        'Xoffset',offsets('xVT'),...
        'Yoffset',offsets('yVT'),...
        'Zoffset',offsets('zVT'));
end
hold off;
end

